# Generated by Django 5.1.2 on 2024-10-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="custom_category",
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={},
        ),
        migrations.RemoveField(
            model_name="contact",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="email",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="instagram_handle",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="last_contact",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="note",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="uploaded_document",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="work",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="birthday",
        ),
        migrations.AlterField(
            model_name="contact",
            name="category",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("personal", "Personal"),
                    ("family", "Family"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
