# Generated by Django 5.1.2 on 2024-10-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0002_remove_contact_custom_category_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="category",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("personal", "Personal"),
                    ("family", "Family"),
                    ("alumni", "Alumni"),
                    ("other", "Other"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
    ]
