# Generated by Django 5.1.2 on 2024-10-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0003_alter_contact_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="instagram_handle",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_contact",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="uploaded_document",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="contact",
            name="work",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
