# Generated by Django 5.1.2 on 2024-10-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0004_contact_birthday_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
